ICT2106project/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICT2106project.DAL;
using ICT2106project.Models;

namespace ICT2106project.Controllers
{
    public class BookController : Controller
    {
        //private BookGateway bookGateway = new BookGateway();
        private DataGateway<Book> DataGateway = new DataGateway<Book>();

        public BookController()
        {
            DataGateway = new BookGateway();
        }
        // GET: Book
        public ActionResult Index()
        {
            return View(DataGateway.SelectAll());
        }

        // GET: Book/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = DataGateway.SelectById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "bookTitle,bookAuthor,bookGenre,bookDesc,bookISBN10,bookISBN13,bookType,bookImage,bookLocation,bookQuantity,bookAvailability,dateOfLoan")] Book book)
        {
            if (ModelState.IsValid)
            {
                DataGateway.Insert(book);
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = DataGateway.SelectById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "bookTitle,bookAuthor,bookGenre,bookDesc,bookISBN10,bookISBN13,bookType,bookImage,bookLocation,bookQuantity,bookAvailability,dateOfLoan")] Book book)
        {
            if (ModelState.IsValid)
            {
                DataGateway.Update(book);
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = DataGateway.SelectById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DataGateway.Delete(id);
            return RedirectToAction("Index");
        }

        /*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

ICT2106project/Controllers/BorrowCartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICT2106project.DAL;
using ICT2106project.Models;
using System.Collections;

namespace ICT2106project.Controllers
{
    public class BorrowCartController : Controller
    {
        private BookGateway bookGateway = new BookGateway();
        static List<Book> cart = new List<Book>();

        // GET: BorrowCart
        public ActionResult Index()
        {
            return View(cart);
        }
        
        // BorrowCart/Add
        public ActionResult Add(int id)
        {
            try
            {
                // Adding book to borrow cart
                Book book = bookGateway.SelectById(id);
                /*Book cartBook = new Book();
                cartBook.bookTitle = book.bookTitle;
                cartBook.bookAuthor = book.bookAuthor;
                cartBook.bookGenre = book.bookGenre;
                cartBook.bookDesc = book.bookDesc;
                cartBook.bookISBN10 = book.bookISBN10;
                cartBook.bookISBN13 = book.bookISBN13;
                cartBook.bookType = book.bookType;
                cartBook.bookImage = book.bookImage;
                cartBook.bookLocation = book.bookLocation;
                cartBook.bookQuantity = book.bookQuantity;
                cartBook.bookAvailability = book.bookAvailability;*/

                //cart.Add(cartBook);
                cart.Add(book);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // BorrowCart/Delete
        public ActionResult Delete(int id)
        {
            cart.RemoveAt(id-1);
            return RedirectToAction("Index");
        }

        // BorrowCart/DeleteAll
        public void DeleteAll()
        {
            cart = new List<Book>();
        }

        // BorrowCart/Checkout
        public ActionResult Checkout()
        {
            TempData["Cart"] = cart;
            cart = new List<Book>();
            return RedirectToAction("Index", "Loan");
        }

    }
}

ICT2106project/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICT2106project.DAL;
using ICT2106project.Models;
using System.Collections;

namespace ICT2106project.Controllers
{
    public class LoanController : Controller
    {
        //private LoanGateway loanGateway = new LoanGateway();
        private DataGateway<Loan> DataGateway = new DataGateway<Loan>();

        public LoanController()
        {
            DataGateway = new LoanGateway();
        }
        // GET: Loan
        public ActionResult Index()
        {
            // Creating loan from checkout
            if (TempData.ContainsKey("Cart"))
            {
                Loan loan = new Loan();
                loan.books = TempData["Cart"] as List<Book>;

                loan.dateOfLoan = DateTime.Today;
                loan.loanQuantity = loan.books.Count;
                loan.loanStatus = "On Loan";
                DataGateway.Insert(loan);
            }
            return View(DataGateway.SelectAll());
        }
    }
}

ICT2106project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Library Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    @if (IsSectionDefined("AddToHead"))
    {
        @RenderSection("AddToHead", required: false)
    }

    @RenderSection("AddToHeadAnotherWay", required: false)
</head>
<body>
    <div class="container toppad">
        <img src="~/Content/images/logo.jpg" alt="LMS Logo" height="50" width="110" class="pull-left">
        @Html.ActionLink("Library Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        @Html.Partial("_LoginPartial")
    </div>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--Dynamic display for different types of users-->
                    @if (User.IsInRole("Librarian"))
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Books", "Index", "Book")</li>
                        <li>@Html.ActionLink("Pending Loans", "Index", "Loan")</li>
                        <li>@Html.ActionLink("Returned Books", "Index", "Loan")</li>
                    }
                    else if (User.IsInRole("Borrower"))
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Books", "Index", "Book")</li>
                        <li>@Html.ActionLink("View Loan Period", "Index", "Loan")</li>
                        <li>@Html.ActionLink("Borrow Cart", "Index", "BorrowCart")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Books", "Index", "Book")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; ICT2106 Project - LMS @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>